
[[view]]
name = "main"

[[draw]]
name = "stack"
mesh = "stack"
shader = "mesh_pc"
camera = "vp"
depth = true

[[draw]]
name = "reticle"
mesh = "reticle"
shader = "mesh_pc"
ortho = "vp"

[[stack]]
id = 1
draw = "stack"
height = 1

[[ui]]
name = "reticle"
draw = "reticle"
width = 8
height = 8
