
[scene]
name = "empty"

[[scene.prop]]
mesh = "debug-grid"
layout = [
    [0.0, 0.0, 0.0],
]

[[scene.prop]]
mesh = "box"
collision = "dop6"
layout = [
    [0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0, 1.0, 100.0],
    [0.0, 5.0, 0.0],
]
