
// Registers
const REG_FRAME = 0;
const REG_WIDTH = 1;
const REG_HEIGHT = 2;
const REG_PROCESS_TIME = 3;
const REG_DELTA_TIME = 4;

const REG_GAME_MODE = 10;

const REG_DEVICE_MODE = 20;
const REG_DEVICE_MOUSE_CHANGED = 21;
const REG_DEVICE_KEYBOARD_CHANGED = 22;
const REG_DEVICE_TOUCH_CHANGED = 23;
const REG_DEVICE_GAMEPAD_CHANGED = 24;

const REG_ACT_MOVE_F = 30;
const REG_ACT_MOVE_S = 31;
const REG_ACT_CAMERA_MOVE_V = 32;
const REG_ACT_CAMERA_MOVE_H = 33;
const REG_ACT_LEFT_HAND = 34;
const REG_ACT_RIGHT_HAND = 35;
const REG_ACT_ACTIVATE = 36;

const REG_POINTER_START_X = 40;
const REG_POINTER_START_Y = 41;
const REG_POINTER_END_X = 42;
const REG_POINTER_END_Y = 43;
const REG_POINTER_STATE = 44;

const REG_REQUEST_RESUME = 60;

const REG_MAX = 128;

// GameMode
const GAME_MODE_PAUSE = 0;
const GAME_MODE_ACTIVE = 1;

// DeviceMode
const DEVICE_MODE_GAMEPAD = 0;
const DEVICE_MODE_MOUSE_KEYBOARD = 1;
const DEVICE_MODE_TOUCH = 2;

// PointerState
const POINTER_STATE_FREE = 0;
const POINTER_STATE_START = 1;
const POINTER_STATE_MOVING = 2;
const POINTER_STATE_END = 3;
