name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get
        run: go get ./cmd/basilico
      - name: Build
        run: go build -ldflags '-s -w' ./cmd/basilico
      - name: Test
        run: go test
