name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Get
      run: go get
    - name: Build
      run: go build
    - name: Test
      run: go test
