name: upload-artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux-amd64, windows-amd64]
        include:
        - os: linux-amd64
          goos: linux
          arch: amd64
        - os: windows-amd64
          goos: windows
          arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get
        run: go get ./...
      - name: Test
        run: go test ./...
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
        run: go build -ldflags '-s -w' -trimpath -o dist/ ./cmd/...
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: basilico-${{ matrix.os }}
          path: dist/
  doc:
    runs-on: ubuntu-latest
    name: Upload Document
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate GoDoc
      uses: ktr0731/godoc-action@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages