name: upload-artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux-amd64, windows-amd64]
        include:
        - os: linux-amd64
          goos: linux
          arch: amd64
        - os: windows-amd64
          goos: windows
          arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Get
        run: go get ./...
      - name: Test
        run: go test ./...
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
        run: go build -ldflags '-s -w' -trimpath -o dist/ ./cmd/...
